# Generated by Django 3.2.7 on 2021-09-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfig',
            name='cover_image',
            field=models.ImageField(default='/logo.png', upload_to='cover_images/'),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='profile_image',
            field=models.ImageField(default='/logo.png', upload_to='profile_images/'),
        ),
    ]
