# Generated by Django 3.2.7 on 2021-09-10 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210905_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64)),
                ('x_field', models.IntegerField(default=400)),
                ('y_field', models.IntegerField(default=200)),
                ('x_space', models.IntegerField(default=1200)),
                ('y_space', models.IntegerField(default=600)),
                ('seat_radius', models.IntegerField(default=60)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurazione palestra',
                'verbose_name_plural': 'Configurazioni palestre',
            },
        ),
    ]
