# Generated by Django 3.2.7 on 2021-09-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_gymconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymconfig',
            old_name='x_space',
            new_name='width_space',
        ),
    ]
