# Generated by Django 3.2.7 on 2021-09-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210904_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('MASCHILE', 'MASCHILE'), ('FEMMINILE', 'FEMMINILE'), ('MINIVOLLEY', 'MINIVOLLEY')], max_length=256, null=True, verbose_name='Categoria'),
        ),
    ]
