# Generated by Django 3.2.7 on 2021-09-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20210904_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Girone'),
        ),
    ]
