# Generated by Django 3.2.7 on 2021-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20210904_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
