# Generated by Django 3.2.7 on 2021-09-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20210904_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(blank=True, max_length=1, null=True, verbose_name='Longitudine'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(blank=True, max_length=1, null=True, verbose_name='Longitudine'),
        ),
    ]
