# Generated by Django 3.2.7 on 2021-09-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='seats',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='reservation.seat'),
        ),
    ]
