# Generated by Django 3.2.7 on 2021-09-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_auto_20210911_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatgymconfig',
            name='left_field',
        ),
        migrations.RemoveField(
            model_name='seatgymconfig',
            name='top_field',
        ),
    ]
