# Generated by Django 3.2.7 on 2021-09-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Canvas',
                'verbose_name_plural': 'Canvas',
            },
        ),
        migrations.CreateModel(
            name='CanvasElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('top', models.IntegerField(default=0)),
                ('left', models.IntegerField(default=0)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.canvas')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('longitude', models.FloatField(blank=True, max_length=1, null=True, verbose_name='Longitudine')),
                ('latitude', models.FloatField(blank=True, max_length=1, null=True, verbose_name='Longitudine')),
                ('manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.manager')),
            ],
            options={
                'verbose_name': 'Luogo',
                'verbose_name_plural': 'Luogo',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('canvaselement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservation.canvaselement')),
            ],
            options={
                'verbose_name': 'Posto a sedere',
                'verbose_name_plural': 'Posti a sedere',
            },
            bases=('reservation.canvaselement',),
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('canvaselement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservation.canvaselement')),
            ],
            options={
                'verbose_name': 'Forma',
                'verbose_name_plural': 'Forme',
            },
            bases=('reservation.canvaselement',),
        ),
        migrations.CreateModel(
            name='PlaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.place')),
            ],
            options={
                'verbose_name': 'Configurazione luogo',
                'verbose_name_plural': 'Configurazioni luoghi',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateTimeField(default=None)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.place')),
            ],
        ),
        migrations.AddField(
            model_name='canvas',
            name='placeconfig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.placeconfig'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.seat')),
            ],
            options={
                'verbose_name': 'Prenotazione',
                'verbose_name_plural': 'Prenotazioni',
            },
        ),
    ]
