# Generated by Django 3.2.7 on 2021-09-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament_day',
            field=models.IntegerField(default=1),
        ),
    ]
