# Generated by Django 3.2.7 on 2021-09-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_match_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='latitude',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Longitudine'),
        ),
        migrations.AddField(
            model_name='gym',
            name='longitude',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Longitudine'),
        ),
    ]
