# Generated by Django 3.2.7 on 2021-09-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_alter_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gym', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='reservation.gym')),
            ],
            options={
                'verbose_name': 'Posto a sedere',
                'verbose_name_plural': 'Posti a sedere',
            },
        ),
    ]
