# Generated by Django 3.2.7 on 2021-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_auto_20210907_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
