# Generated by Django 3.2.7 on 2021-09-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_gymconfig_user'),
        ('reservation', '0015_auto_20210907_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='x',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='y',
        ),
        migrations.CreateModel(
            name='SeatGymConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=69)),
                ('y', models.IntegerField(default=69)),
                ('gym', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.gymconfig')),
                ('seat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='reservation.seat')),
            ],
        ),
    ]
