# Generated by Django 3.2.7 on 2021-09-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_auto_20210911_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatgymconfig',
            old_name='x',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='seatgymconfig',
            old_name='y',
            new_name='top',
        ),
    ]
