# Generated by Django 3.2.7 on 2021-09-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_auto_20210907_2346'),
        ('authentication', '0005_auto_20210911_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymconfig',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='reservation.gym'),
        ),
    ]
