# Generated by Django 3.2.7 on 2021-09-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_gymconfig_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymconfig',
            old_name='user',
            new_name='gym',
        ),
    ]
